version: '3.3'

services:
#  pm2-app:
#    build: .
#    volumes:
#    - ./src:/src
#    - ./logs/pm2-app:/root/.pm2/logs
#    ports:
#    - '8000:80'
#    depends_on:
#    - mongo

  mongo:
    image: mongo:latest
    container_name: "twig-bookmark"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
